### ISSUE TITLE
`tnrs_match_names` does not return the best match in some cases 

### ISSUE THREAD

**Issue by ajrominger** [ropensci/rotl#143] opened 2023-05-31 19:12 UTC
Thanks very much for this package!  I'm trying to figure out why `tnrs_match_names` is not returning the best match for at least some/certain queries where fuzzy matching is used.

Here's an example:

    library(rotl)

    # should match to Psoloessa texana ----
    ghop <- tnrs_match_names("Psoloessa texan") 

    # all good (note: `ghop$number_matches` is 1)
    ghop

    ##     search_string      unique_name approximate_match  ott_id is_synonym flags   number_matches
    ## 1 psoloessa texan Psoloessa texana              TRUE 3498865      FALSE                      1

    # should match to Drosophila sproati ----
    fly <- tnrs_match_names("Drosophila sproat") 

    # not all good (note: `fly$number_matches` is 4)
    fly

    ##       search_string        unique_name approximate_match ott_id is_synonym  flags number_matches
    ## 1 drosophila sproat Drosophila serrata              TRUE  86632      FALSE                     4

Digging deeper into why that is, I looked at the original query output and found

    fly_all <- attr(fly, "original_response")
    fly_all$results[[1]]$matches[[1]]$score

    ## [1] 0.9444444

    fly_all$results[[1]]$matches[[1]]$taxon$unique_name

    ## [1] "Drosophila sproati"

So the first hit is for *Drosophila sproati* as we expect. The **second** hit is

    fly_all$results[[1]]$matches[[2]]$score

    ## [1] 0.8333333

    fly_all$results[[1]]$matches[[2]]$taxon$unique_name

    ## [1] "Drosophila serrata"

Which gives us *Drosophila serrata*, and that result is what’s returned in the `data.frame` of `fly`.

So I guess the short question, and issue, is why is `tnrs_match_names` returning the **second** hit, which in this case has a substantially lower match score than the first hit? Can this be fixed?

Thanks for fielding this issue, and thanks again so much for the package!

**Comment by fmichonneau** [comment] 2023-06-06 20:21
Thanks for the report @ajrominger! It looks like a duplicate of #127.
I'll see if I can have a look this weekend.

**Comment by ajrominger** [comment] 2023-06-06 21:11
Thanks! One thing to highlight in relation to #127 is that `rotl:::.tnrs_match_names("lacerta_agilis")` (the example used in #127) only returns 2 matches whereas `rotl:::.tnrs_match_names("Drosophila sproat")` (the example used in this issue) returns 4 matches, and the thing that surprises me is that the 2nd of these matches is returned by `rotl::tnrs_match_names`. If the first or last match was returned then it would seem like a sorting issue, but the 2nd match just surprised me.

providing this context only in the hope of being helpful!

**Closed** 2023-06-12 13:41 UTC

**Comment by fmichonneau** [comment] 2023-06-12 13:42
Hi @ajrominger, can you please install the latest version of the package from GitHub and confirm that it now behaves as expected? If not, please re-open the issue, otherwise, I'll send this new version to CRAN later this week. Thanks for raising this issue!

**Comment by ajrominger** [comment] 2023-06-12 18:00
looks good to me! thanks @fmichonneau!
